root:
  id: "base"
  color: [0.33, 0.33, 0.33]
  power: 3.0
  model: "models/base.stl"
  type: "table"
  position: [0, 0, 0, 0, 0, 0]
  origin: [0, 0, 0]
  axis: null
  joint: null
  child_r_l0:
    id: "joint_0"
    color: [0.33, 0.33, 0.33]
    power: 3.0
    model: "models/joint_0.stl"
    type: "angular"
    position: [0, 0, 90, 0, 0, 0]
    origin: [0, 0, 90]
    axis: "z"
    joint: 0
    child_r_l1:
      id: "joint_1"
      color: [0.33, 0.33, 0.33]
      power: 3.0
      model: "models/joint_1.stl"
      type: "angular"
      position: [0, 0, 135, 0, 0, 0]
      origin: [0, 0, 135]
      axis: "y"
      joint: 1
      child_r_l2:
        id: "joint_2"
        color: [0.33, 0.33, 0.33]
        power: 3.0
        model: "models/joint_2.stl"
        type: "angular"
        position: [135, 0, 135, 0, 0, 0]
        origin: [135, 0, 135]
        axis: "y"
        joint: 2
        child_r_l3:
          id: "joint_3"
          color: [0.33, 0.33, 0.33]
          power: 3.0
          model: "models/joint_3.stl"
          type: "angular"
          position: [170, 0, 70, 0, 0, 0]
          origin: [170, 0, 70]
          axis: "-z"
          joint: 3
          child_r_l4:
            id: "joint_4"
            color: [0.33, 0.33, 0.33]
            power: 3.0
            model: "models/joint_4.stl"
            type: "angular"
            position: [170, 0, 15, 0, 0, 0]
            origin: [170, 0, 15]
            axis: "y"
            joint: 4
