root:
    id: "table"
    color: [0.33, 0.33, 0.33]
    power: 3.0
    model: "models/table.stl"
    type: "table"
    position: [0, 0, 0, 0, 0, 0]
    origin: [0, 0, 0]
    axis: null
    joint: null
    root:
        id: "table_1"
        color: [0.33, 0.33, 0.33]
        power: 3.0
        model: "models/arm_base.stl"
        type: "table"
        position: [0, 0, 0, 0, 0, 0]
        origin: [0, 0, 0]
        axis: null
        joint: null
        child_r_l0:
            id: "joint_0"
            color: [0.33, 0.33, 0.33]
            power: 3.0
            model: "models/arm_joint_0.stl"
            type: "angular"
            position: [0, 0, 3, 0, 0, 0]
            origin: [0, 0, 3]
            axis: "z"
            joint: 0
            child_r_l1:
                id: "joint_1"
                color: [0.33, 0.33, 0.33]
                power: 3.0
                model: "models/arm_joint_1.stl"
                type: "angular"
                position: [0, 0, 7, 0, 0, 0]
                origin: [0, 0, 7]
                axis: "x"
                joint: 1
                child_r_l2:
                    id: "joint_2"
                    color: [0.33, 0.33, 0.33]
                    power: 3.0
                    model: "models/arm_joint_2.stl"
                    type: "angular"
                    position: [0, 0, 16, 0, 0, 0]
                    origin: [0, 0, 16]
                    axis: "x"
                    joint: 2
                    child_r_l3:
                        id: "joint_3"
                        color: [0.33, 0.33, 0.33]
                        power: 3.0
                        model: "models/arm_joint_3.stl"
                        type: "angular"
                        position: [0, -5, 16, 0, 0, 0]
                        origin: [0, -5, 16]
                        axis: "-z"
                        joint: 3
                        child_r_l4:
                            id: "joint_4"
                            color: [0.33, 0.33, 0.33]
                            power: 3.0
                            model: "models/arm_joint_4.stl"
                            type: "angular"
                            position: [0, -9, 16, 0, 0, 0]
                            origin: [0, -9, 16]
                            axis: "x"
                            joint: 4

