 root:
    id: "frame"
    model: ""
    type: "table"
    position: [0, 0, 0, 0, 0, 0]
    origin: [0, 0, 0]
    axis: null
    joint: null
    child_saddle:
        id: "saddle"
        model: ""
        type: "linear"
        position: [0, 0, 0, 0, 0, 0]
        origin: [0, 0, 0]
        axis: "y"
        joint: 0
        child_table:
            id: "table"
            model: ""
            type: "linear"
            position: [0, 0, 0, 0, 0, 0]
            origin: [0, 0, 0]
            axis: "x"
            joint: 1  
            child_a_axis:
               id: "chuck"
               model: ""
               type: "angular"
               position: [0, 0, -18, 0, 0, 0]
               origin: [0, 0, -18]
               axis: "a"
               joint: 3

    child_headstock:
        id: "headstock"
        model: ""
        type: "linear"
        position: [0, 0, 0, 0, 0, 0]
        origin: [0, 0, 0]
        axis: "z"
        joint: 2
    