[EMC]
VERSION = 1.1
MACHINE = QtPyVCP - probe_basic Sim
DEBUG = 0

[DISPLAY]
DISPLAY = probe_basic
THEME_COLOR = system
ANTIALIAS = true
FPS = 60
OPEN_FILE = /home/pyside6-test/dev/probe_basic/example_gcode/blank.ngc
CONFIRM_EXIT = False
LOG_FILE = sim.log
LOG_LEVEL = DEBUG
ADVANCED_LOGGING = False
PREFERENCE_FILE = sim.pref
CONFIG_FILE = custom_config.yml
POSITION = 0x0
DCONE_BASESIZE =            0.25
POSITION_OFFSET = RELATIVE
POSITION_FEEDBACK = ACTUAL
MAX_FEED_OVERRIDE = 2.000000
MAX_SPINDLE_OVERRIDE = 2.000000
MIN_SPINDLE_OVERRIDE = 0.500000
DEFAULT_SPINDLE_SPEED = 300
DEFAULT_LINEAR_VELOCITY = 10.00000
MAX_LINEAR_VELOCITY = 10.000000
MIN_LINEAR_VELOCITY = 0.016670
DEFAULT_ANGULAR_VELOCITY = 36.000000
MAX_ANGULAR_VELOCITY = 360.000000
MIN_ANGULAR_VELOCITY = 1.666667
PROGRAM_PREFIX = /home/pyside6-test/dev/probe_basic/example_gcode
INTRO_GRAPHIC = pbsplash.png
INTRO_TIME = 5
INCREMENTS = JOG .01in .001in .0001in
GEOMETRY = xyzabc
#USER_TABS_PATH = user_tabs/
USER_BUTTONS_PATH = user_buttons/
USER_DROS_PATH = user_dro_display/
DRO_DISPLAY = user
GEOMETRY = XYZABC
OFFSET_COLUMNS = XYZABCR
TOOL_TABLE_COLUMNS = TZDR
KEYBOARD_JOG = true
KEYBOARD_JOG_SAFETY_OFF = true
# ATC tab display options, 0 = no atc tab displayed, 1 = Carousel atc display, 2 = rack atc display
ATC_TAB_DISPLAY = 0
#USER_ATC_BUTTONS_PATH = user_atc_buttons/

# File Paths:
#   File paths can be relative to the config dir:
#     LOG_FILE = qtpyvcp.log
#   Or relative to $HOME: (May not be compatible with other GUIs!)
#     LOG_FILE = ~/qtpyvcp.log
#   Or at an absolute location:
#     LOG_FILE = /home/<USER>/qtpyvcp.log
#   Enviroment vars are also expanded:
#     LOG_FILE = $CONFIG_DIR/qtpyvcp.log

[FILTER]
PROGRAM_EXTENSION = .nc,.txt,.tap Other NC files
PROGRAM_EXTENSION = .png,.gif,.jpg Greyscale Depth Image
    png = image-to-gcode
    gif = image-to-gcode
    jpg = image-to-gcode

[ATC]
# Carousel images are available for 8, 10, 12, 14, 16, 18, 20, 21, 24 pocket changers
POCKETS = 12
# The Z height your spindle needs to be at to clamp/unclamp a tool from the ATC platter
Z_TOOL_CHANGE_HEIGHT = -3.1900
# The Z clearance height in machine coordinates your spindle needs to be at to clear the tools during carousel rotation 
Z_TOOL_CLEARANCE_HEIGHT = 0.0000
# Step Time should be set to the approximate time it takes your ATC to rotate from one pocket to the next entry is in milliseconds(1 second = 1000ms)
# This just adjust the speed of the ATC tab Carousel GFX rotation (default if omitted is 1000ms)
STEP_TIME = 500

[RS274NGC]
RS274NGC_STARTUP_CODE = F10 S300 G20 G17 G40 G49 G54 G64 P0.001 G80 G90 G91.1 G92.1 G94 G97 G98
PARAMETER_FILE = sim.var
OWORD_NARGS = 1
NO_DOWNCASE_OWORD = 1
SUBROUTINE_PATH = subroutines
ON_ABORT_COMMAND = O<on_abort> CALL

[EMCMOT]
EMCMOT =           motmod
BASE_PERIOD =      50000
SERVO_PERIOD =     1000000
TRAJ_PERIOD =      100000
COMM_TIMEOUT =     1.0
HOMEMOD =          homemod

[TASK]
TASK = milltask
CYCLE_TIME = 0.010

[HAL]
HALFILE = sim-robot_arm-core.hal
HALFILE = sim-robot_arm-joints.hal
HALFILE = robot_arm-kinematics.hal
POSTGUI_HALFILE = robot_arm-postgui.hal

# HALFILE = hallib/core_sim_3.hal
# HALFILE = hallib/simulated_home_probe_basic_3.hal
# HALFILE = hallib/spindle_sim.hal
# HALFILE = hallib/sim_cannon.hal
HALUI = halui
# POSTGUI_HALFILE = hallib/probe_basic_postgui.hal
TWOPASS = on

[HALUI]

[VTK]
CPP_BACKPLOT = 0
TRANSFORM_DEBUG = 1
ARC_DIVISION = 128
MACHINE_PARTS = models/robot_arm.yml
TOOL_CONE_FOLLOW_SPINDLE_PART = 1
SPINDLE_PART_ID = spindle
MOTION_MODE = joint
X = head
Y = head
Z = head
A = head
B = head
C = head

[TRAJ]
AXES = 6
COORDINATES =                  X Y Z A B C
ARC_BLEND_ENABLE =             1
ARC_BLEND_FALLBACK_ENABLE =    0
ARC_BLEND_OPTIMIZATION_DEPTH = 50
ARC_BLEND_GAP_CYCLES =         4
ARC_BLEND_RAMP_FREQ =          100
SPINDLES =                     1
LINEAR_UNITS =                 inch
ANGULAR_UNITS =                deg
DEFAULT_LINEAR_VELOCITY =      1.0
MAX_LINEAR_VELOCITY =          10.0
DEFAULT_LINEAR_ACCELERATION =  10.0
MAX_LINEAR_ACCELERATION =      20.0
MAX_ANGULAR_VELOCITY =         360.0
NO_FORCE_HOMING =              0
HOME =                         7.726875 -7.509659 0.494981 93.290672 19.408774 -0.334399

[EMCIO]
EMCIO = io
CYCLE_TIME = 0.100
TOOL_CHANGE_POSITION = 7.726875 -7.509659 0.494981 93.290672 19.408774 -0.334399
TOOL_TABLE = tool.tbl

[KINS]
KINEMATICS = genserkins coordinates=xyzabc
JOINTS =     6

[AXIS_X]
MAX_VELOCITY =     1000
MAX_ACCELERATION = 1500
MIN_LIMIT =       -15.0
MAX_LIMIT =        15.0

[AXIS_Y]
MAX_VELOCITY =     1000
MAX_ACCELERATION = 1500
MIN_LIMIT =       -26.0
MAX_LIMIT =         6.0

[AXIS_Z]
MAX_VELOCITY =     1000
MAX_ACCELERATION = 1500
MIN_LIMIT =        -2.0
MAX_LIMIT =        36.0

[AXIS_A]
MAX_VELOCITY =     1000
MAX_ACCELERATION = 1500

[AXIS_B]
MAX_VELOCITY =     1000
MAX_ACCELERATION = 1500

[AXIS_C]
MAX_VELOCITY =     1000
MAX_ACCELERATION = 1500

[JOINT_0]
NAME =               A1
TYPE =               ANGULAR
MAX_VELOCITY =       180
MAX_ACCELERATION =   50000
MIN_LIMIT =         -180.0
MAX_LIMIT =          180.0
FERROR =             1.00
MIN_FERROR =         100
DEADBAND =           0
MAX_OUTPUT =         1.00
MAX_ERROR =          100
HOME =                  0
HOME_OFFSET =           0
HOME_SEARCH_VEL =       0
HOME_LATCH_VEL =        0
HOME_USE_INDEX =        NO
HOME_ABSOLUTE_ENCODER = 1
HOME_SEQUENCE =         0
BIAS = 0
P =    0
I =    0
D =    0
FF0 =  0
FF1 =  0
FF2 =  0

[JOINT_1]
NAME =               A2
MAX_VELOCITY =       180
MAX_ACCELERATION =   50000
TYPE =               ANGULAR
MIN_LIMIT =          -65
MAX_LIMIT =           90
FERROR =             1.00
MIN_FERROR =          100
DEADBAND =              0
MAX_OUTPUT =         1.00
MAX_ERROR =           100
HOME =                  -20
HOME_OFFSET =           -20
HOME_SEARCH_VEL =       0
HOME_LATCH_VEL =        0
HOME_USE_INDEX =        NO
HOME_ABSOLUTE_ENCODER = 1
HOME_SEQUENCE =         0
BIAS = 0
P =    0
I =    0
D =    0
FF0 =  0
FF1 =  0
FF2 =  0

[JOINT_2]
NAME =               A
TYPE =               ANGULAR
MAX_VELOCITY =       180
MAX_ACCELERATION =   50000
MIN_LIMIT =         -90.0
MAX_LIMIT =          70.0
FERROR =             1.00
MIN_FERROR =         100
DEADBAND =           0
MAX_OUTPUT =         1.00
MAX_ERROR =          100
HOME =                  20
HOME_OFFSET =           20
HOME_SEARCH_VEL =       0
HOME_LATCH_VEL =        0
HOME_USE_INDEX =        NO
HOME_ABSOLUTE_ENCODER = 1
HOME_SEQUENCE =         0
BIAS = 0
P =    0
I =    0
D =    0
FF0 =  0
FF1 =  0
FF2 =  0

[JOINT_3]
NAME =               A4
TYPE =               ANGULAR
MAX_VELOCITY =       300
MAX_ACCELERATION =   50000
MIN_LIMIT =         -135.0
MAX_LIMIT =          135.0
FERROR =             1.00
MIN_FERROR =         100
DEADBAND =           0
MAX_OUTPUT =         1.00
MAX_ERROR =          100
HOME =                  10
HOME_OFFSET =           10
HOME_SEARCH_VEL =       0
HOME_LATCH_VEL =        0
HOME_USE_INDEX =        NO
HOME_ABSOLUTE_ENCODER = 1
HOME_SEQUENCE =         0
BIAS = 0
P =    0
I =    0
D =    0
FF0 =  0
FF1 =  0
FF2 =  0

[JOINT_4]
NAME =               A5
TYPE =               ANGULAR
MAX_VELOCITY =       300
MAX_ACCELERATION =   50000
MIN_LIMIT =         -115.0
MAX_LIMIT =          115.0
FERROR =             1.00
MIN_FERROR =         100
DEADBAND =           0
MAX_OUTPUT =         1.00
MAX_ERROR =          100
HOME =                  20
HOME_OFFSET =           20
HOME_SEARCH_VEL =       0
HOME_LATCH_VEL =        0
HOME_USE_INDEX =        NO
HOME_ABSOLUTE_ENCODER = 1
HOME_SEQUENCE =         0
BIAS = 0
P =    0
I =    0
D =    0
FF0 =  0
FF1 =  0
FF2 =  0

[JOINT_5]
NAME =               A6
TYPE =               ANGULAR
MAX_VELOCITY =       500
MAX_ACCELERATION =   50000
MIN_LIMIT =         -720.0
MAX_LIMIT =          720.0
FERROR =             1.00
MIN_FERROR =         100
DEADBAND =           0
MAX_OUTPUT =         1.00
MAX_ERROR =          100
HOME =                  10
HOME_OFFSET =           10
HOME_SEARCH_VEL =       0
HOME_LATCH_VEL =        0
HOME_USE_INDEX =        NO
HOME_ABSOLUTE_ENCODER = 1
HOME_SEQUENCE =         0
BIAS = 0
P =    0
I =    0
D =    0
FF0 =  0
FF1 =  0
FF2 =  0

#==================
#     Spindle
#==================

[SPINDLE_9]
P = 0
I = 0
D = 0
FF0 = 1
FF1 = 0
FF2 = 0
BIAS = 0
DEADBAND = 0
MAX_OUTPUT = 2000
